all:
	gcc guia_sincro-ej6.c -oguia_sincro-ej6 -lpthread -g
	gcc th_race.c -oth_race -g -lpthread
	gcc th_race.c -oth_race_opt -g -lpthread -O3
	gcc th_race_nthreads.c -oth_race_nthreads -g -lpthread -O3
